spring.application.name=worker-process
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=product-worker-group
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:db_pass}
spring.jpa.hibernate.ddl-auto=validate
